theme: jekyll-theme-minimal

title: [My Personal Footprint Reduction Plan]
description: [How to start reducing your footprint]

logo: [Location of the logo]
show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]

